### ISSUE TITLE
UNRATED I 0 RP I -300 elo #106 

### ISSUE THREAD

**Issue by Prakhar333** [RumbleMike/ValorantStreamOverlay#126]

**Comment by ElvioG** [comment]
Same for me... even after the update the problem persists
I play since beta, ranked from ACT I
![ValorantStreamOverlay_2021-01-07_11-57-24](https://user-images.githubusercontent.com/3685079/103884742-475ae380-50df-11eb-86e1-982667dbe6c4.png)

**Comment by Koupah** [comment]
It says -300 elo because Iron 1 is technically Rank 3, so for you to be at Rank 0 (Unrated) thats 3 ranks below Iron 1.
Each rank is 100 elo therefore by being unrated you have -300 elo.

This can't detect your elo unless you have your rank as the elo is fetched FROM ranked games, if you play 20 unrated games after playing a ranked (as Gold 3, for example) it will show as Unrated because there is no game to get the information from.

**Comment by ElvioG** [comment]
I'm rank Gold 2

**Comment by ElvioG** [comment]
Ok, thank you :)

**Comment by Prakhar333** [comment]
AFTER updating it to latest release my issue got fixed ..
